-- Phase B: lead capture for the guaraplatform.com MVP form.
--
-- Storage conventions
--   * Multi-select answers (interests, infrastructure) are JSON arrays of enum codes,
--     e.g. '["pilot","licensing"]'. Query them with json_each(), e.g.
--       SELECT l.id FROM leads l, json_each(l.interests) i WHERE i.value = 'licensing';
--   * Single-select answers are stored as their enum code (see src/lead.js for the allowed values).
--   * Timestamps are server-generated ISO 8601 UTC strings.
--   * status and internal_notes are written only by GUARA staff, never by the public form.
--
-- Deliberately NOT stored: IP address, user agent, browser fingerprint, full referrer URL,
-- passwords, identity numbers, biometrics or uploaded files.
--
-- Retention: no automatic deletion is implemented. The retention period is an open decision
-- that must be approved before this table receives production data.

CREATE TABLE leads (
  id                      TEXT PRIMARY KEY,                    -- random UUID generated by the Worker
  created_at              TEXT NOT NULL,                       -- server time, ISO 8601 UTC
  language                TEXT NOT NULL CHECK (language IN ('en', 'es')),
  page_source             TEXT,                                -- path of the page that submitted the form, e.g. '/es/'
  intent_source           TEXT,                                -- CTA intent that preselected the form, e.g. 'pilot'

  interests               TEXT NOT NULL,                       -- JSON array
  current_situation       TEXT NOT NULL,
  organization_type       TEXT NOT NULL,
  industry                TEXT NOT NULL,
  infrastructure          TEXT NOT NULL,                       -- JSON array
  infrastructure_detail   TEXT,
  operation_scale         TEXT,
  goal                    TEXT,

  name                    TEXT NOT NULL,
  company                 TEXT NOT NULL,
  email                   TEXT NOT NULL,
  country                 TEXT NOT NULL,                       -- ISO 3166-1 alpha-2
  message                 TEXT,

  utm_source              TEXT,
  utm_medium              TEXT,
  utm_campaign            TEXT,
  utm_content             TEXT,

  status                  TEXT NOT NULL DEFAULT 'new' CHECK (status IN (
                            'new', 'reviewed', 'qualified', 'contacted', 'pilot',
                            'integration', 'licensing', 'not_fit', 'closed')),
  internal_notes          TEXT,

  privacy_acknowledged_at TEXT NOT NULL
);

CREATE INDEX idx_leads_created_at ON leads (created_at);
CREATE INDEX idx_leads_status ON leads (status);
